name: meetical_project
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
<<<<<<< HEAD
  http: ^0.13.5
  
=======
  table_calendar: ^3.0.6
  flutter_local_notifications: ^19.2.1   # ✅ <-- AÑADIDO AQUÍ
  timezone: 0.10.1
  pdf: ^3.10.4
  printing: ^5.12.0

>>>>>>> origin/Andy
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
<<<<<<< HEAD
    - assets/imagenes/splash/splash_background.png
    - assets/imagenes/splash/logo.png
    - assets/imagenes/splash/overlay.png
    - assets/imagenes/splash/imagen_blanca.jpg
    - assets/imagenes/login/user_icon.jpg
    - assets/imagenes/register/fondo_registro.png
    - assets/imagenes/register/medico.jpg
    - assets/imagenes/register/paciente.jpg


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
=======
    - assets/images/logo.png
    - assets/sounds/notification.mp3   # ✅ sonido agregado aquí

>>>>>>> origin/Andy



